const allCards = [
  { english: "Water",   kannada: "ನೀರು",   pronoun: "Neeru",   cat: "Nature" },
  { english: "Sun",     kannada: "ಸೂರ್ಯ",  pronoun: "Soorya",  cat: "Nature" },
  { english: "Moon",    kannada: "ಚಂದ್ರ",  pronoun: "Chandra", cat: "Nature" },
  { english: "Tree",    kannada: "ಮರ",     pronoun: "Mara",    cat: "Nature" },
  { english: "Flower",  kannada: "ಹೂವು",   pronoun: "Hoovu",   cat: "Nature" },
  { english: "Mother",  kannada: "ತಾಯಿ",   pronoun: "Taayi",   cat: "Family" },
  { english: "Father",  kannada: "ತಂದೆ",   pronoun: "Tande",   cat: "Family" },
  { english: "Sister",  kannada: "ಅಕ್ಕ",   pronoun: "Akka",    cat: "Family" },
  { english: "Brother", kannada: "ಅಣ್ಣ",   pronoun: "Anna",    cat: "Family" },
  { english: "House",   kannada: "ಮನೆ",    pronoun: "Mane",    cat: "Family" },
  { english: "Rice",    kannada: "ಅನ್ನ",   pronoun: "Anna",    cat: "Food"   },
  { english: "Milk",    kannada: "ಹಾಲು",   pronoun: "Haalu",   cat: "Food"   },
  { english: "Mango",   kannada: "ಮಾವು",   pronoun: "Maavu",   cat: "Food"   },
  { english: "One",     kannada: "ಒಂದು",   pronoun: "Ondu",    cat: "Numbers"},
  { english: "Two",     kannada: "ಎರಡು",   pronoun: "Eradu",   cat: "Numbers"},
  { english: "Three",   kannada: "ಮೂರು",   pronoun: "Mooru",   cat: "Numbers"},
  { english: "Four",    kannada: "ನಾಲ್ಕು", pronoun: "Naalku",  cat: "Numbers"},
  { english: "Five",    kannada: "ಐದು",    pronoun: "Aidu",    cat: "Numbers"},
  { english: "Welcome",   kannada: "ಸುಸ್ವಾಗತ",   pronoun: "Susswaagat",   cat: "Greetings" },
  { english: "Good Morning",   kannada: "ಶುಭೋದಯ",   pronoun: "Shubhodaya",   cat: "Greetings" },
  { english: "Good Night",   kannada: "ಶುಭ ರಾತ್ರಿ",   pronoun: "Shubha Raatri",   cat: "Greetings" },
  { english: "Thank You",   kannada: "ಧನ್ಯವಾದಗಳು",   pronoun: "Dhanyavaadagalu",   cat: "Greetings" },
  { english: "stop",   kannada: "ನಿಲ್ಲಿಸು",   pronoun: "Nillisu",   cat: "Greetings" },
  { english: "please",   kannada: "ದಯವಿಟ್ಟು",   pronoun: "Dayavittu",   cat: "Greetings" },
  { english: "Hello",   kannada: "ನಮಸ್ಕಾರ",   pronoun: "Namaskara",   cat: "Greetings" },
  { english: "Sorry",   kannada: "ಕ್ಷಮಿಸು",   pronoun: "Kshamisu",   cat: "Greetings" },
  { english: "It's Okay",   kannada: "ಇದು ಠೀಕ",   pronoun: "Idu Thik",   cat: "Greetings" },
  { english: "Excuse Me",   kannada: "ಕ್ಷಮಿಸು",   pronoun: "Kshamisu",   cat: "Greetings" },
  { english: "Mountain",   kannada: "ಪರ್ವತ",   pronoun: "Parvata",   cat: "Nature" },
  { english: "River",   kannada: "ನದಿ",   pronoun: "Nadi",   cat: "Nature" },
  { english: "Time",   kannada: "ಸಮಯ",   pronoun: "Samaya",   cat: "Nature" },
  { english: "Fire",   kannada: "ಅಗ್ನಿ",   pronoun: "Agni",   cat: "Nature" },
  { english: "Friend",   kannada: "ಮಿತ್ರ",   pronoun: "Mitra",   cat: "Family" },
  { english: "Food",   kannada: "ಭೋಜನ",   pronoun: "Bhogaana",   cat: "Food"   },
  { english: "Goodbye",   kannada: "ನಮಸ್ಕಾರ",   pronoun: "Namaskara",   cat: "Greetings" },
  { english: "Road",   kannada: "ಮಾರ್ಗ",   pronoun: "Maarga",   cat: "Nature" },
  { english: "yes",   kannada: "ಹೌದು",   pronoun: "Howdu",   cat: "Greetings" },
  { english: "No",   kannada: "ಇಲ್ಲ",   pronoun: "Illa",   cat: "Greetings" },
];
